# Generated by Django 4.2.17 on 2025-06-06 21:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau_competence', models.IntegerField(default=1)),
                ('disponible', models.BooleanField(default=True)),
                ('date_embauche', models.DateField()),
                ('specialites', models.JSONField(default=list)),
                ('centre_appel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.centreappels')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agent',
                'verbose_name_plural': 'Agents',
            },
        ),
    ]
