# Generated by Django 4.2.17 on 2025-06-04 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
        ('missions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('appel_entrant', 'Appel entrant'), ('appel_sortant', 'Appel sortant'), ('email', 'Email'), ('chat', 'Chat'), ('sms', 'SMS'), ('autre', 'Autre')], max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('contenu', models.TextField(blank=True)),
                ('resultat', models.CharField(blank=True, max_length=255)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='core.clientfinal')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='missions.mission')),
            ],
        ),
    ]
