# Generated by Django 4.2.17 on 2025-06-04 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('missions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField(choices=[(1, '1 - Très insatisfait'), (2, '2 - Insatisfait'), (3, '3 - Neutre'), (4, '4 - Satisfait'), (5, '5 - Très satisfait')])),
                ('commentaire', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks_recus', to=settings.AUTH_USER_MODEL)),
                ('evaluateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks_donnes', to=settings.AUTH_USER_MODEL)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='missions.mission')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
