# Generated by Django 4.2.17 on 2025-06-04 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('missions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('valeur', models.FloatField()),
                ('date', models.DateField(auto_now_add=True)),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='core.centreappels')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='core.entreprisedonneuseordre')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='missions.mission')),
            ],
        ),
    ]
