# Generated by Django 4.2.17 on 2025-06-04 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0001_initial'),
        ('missions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaisieResultat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', 'Succès'), ('failure', 'Échec'), ('callback', 'Rappel nécessaire'), ('unavailable', 'Indisponible')], max_length=20)),
                ('commentaire', models.TextField()),
                ('duree_appel', models.DurationField()),
                ('date_appel', models.DateTimeField(auto_now_add=True)),
                ('rappel_prevu', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saisies_resultats', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_saisie', to='clients.client')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats_saisie', to='missions.mission')),
            ],
            options={
                'verbose_name': 'Saisie de résultat',
                'verbose_name_plural': 'Saisies de résultats',
                'ordering': ['-date_appel'],
            },
        ),
    ]
