# Generated by Django 4.2.17 on 2025-06-09 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saisie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saisieresultat',
            name='type_appel',
            field=models.CharField(choices=[('entrant', 'Appel entrant'), ('sortant', 'Appel sortant')], default='sortant', max_length=10),
        ),
    ]
