# Generated by Django 4.2.17 on 2025-06-04 20:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('fichier', models.FileField(upload_to='documents/')),
                ('type', models.CharField(choices=[('contrat', 'Contrat'), ('facture', 'Facture'), ('rapport', 'Rapport'), ('autre', 'Autre')], default='autre', max_length=20)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.entreprisedonneuseordre')),
            ],
            options={
                'ordering': ['-date_modification'],
            },
        ),
    ]
