# Generated by Django 4.2.17 on 2025-06-05 23:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-date_modification'], 'verbose_name': 'Document', 'verbose_name_plural': 'Documents'},
        ),
        migrations.AlterField(
            model_name='document',
            name='entreprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_uploaded', to='core.entreprisedonneuseordre'),
        ),
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('contrat', 'Contrat'), ('facture', 'Facture'), ('autre', 'Autre')], default='autre', max_length=20),
        ),
        migrations.CreateModel(
            name='RapportGenere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('mission', 'Rapport de mission'), ('performance', 'Rapport de performance'), ('financier', 'Rapport financier'), ('activite', "Rapport d'activité")], max_length=20)),
                ('contenu', models.JSONField(help_text='Données utilisées pour générer le rapport')),
                ('date_generation', models.DateTimeField(default=django.utils.timezone.now)),
                ('derniere_consultation', models.DateTimeField(blank=True, null=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_generated', to='core.entreprisedonneuseordre')),
            ],
            options={
                'verbose_name': 'Rapport généré',
                'verbose_name_plural': 'Rapports générés',
                'ordering': ['-date_generation'],
            },
        ),
    ]
