# Generated by Django 4.2.17 on 2025-06-04 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
        ('missions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='rapports/')),
                ('statistiques', models.TextField(blank=True)),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports', to='core.centreappels')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports', to='core.entreprisedonneuseordre')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports', to='missions.mission')),
            ],
        ),
        migrations.CreateModel(
            name='SaisieResultat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicateur', models.CharField(max_length=255)),
                ('valeur', models.CharField(max_length=255)),
                ('statut', models.CharField(choices=[('success', 'Réussi'), ('failure', 'Échec'), ('pending', 'En attente')], default='pending', max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saisies', to=settings.AUTH_USER_MODEL)),
                ('rapport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saisies', to='rapports.rapport')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to=settings.AUTH_USER_MODEL)),
                ('rapport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='rapports.rapport')),
            ],
        ),
    ]
