# Generated by Django 4.2.17 on 2025-06-05 14:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('missions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='agents',
            field=models.ManyToManyField(blank=True, related_name='missions_assignees', to=settings.AUTH_USER_MODEL),
        ),
    ]
