# Generated by Django 4.2.17 on 2025-06-05 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0002_mission_agents'),
    ]

    operations = [
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('quantitatif', 'Quantitatif'), ('qualitatif', 'Qualitatif'), ('temporel', 'Temporel')], max_length=30)),
                ('unite', models.CharField(blank=True, help_text='Unité de mesure (%, heures, appels, etc.)', max_length=50)),
                ('valeur_cible', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='mission',
            name='kpis',
            field=models.ManyToManyField(blank=True, related_name='missions', to='missions.kpi'),
        ),
    ]
