# Generated by Django 4.2.17 on 2025-06-04 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interactions', '0001_initial'),
        ('ai_tools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysesentiment',
            name='interaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analyse_sentiment', to='interactions.interaction'),
        ),
    ]
