# Generated by Django 4.2.17 on 2025-06-06 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0003_remove_formation_mission_formation_duree_and_more'),
        ('agents', '0001_initial'),
        ('ai_tools', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptimisationPlanning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_optimisation', models.DateTimeField(auto_now_add=True)),
                ('score_optimisation', models.FloatField()),
                ('nombre_agents', models.IntegerField()),
                ('nombre_missions', models.IntegerField()),
                ('details', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='RecommandationFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('date_recommandation', models.DateTimeField(auto_now_add=True)),
                ('appliquee', models.BooleanField(default=False)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommandations_formation', to='agents.agent')),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formations.formation')),
            ],
        ),
        migrations.CreateModel(
            name='PredictionPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_prediction', models.DateTimeField(auto_now_add=True)),
                ('kpi_predit', models.FloatField()),
                ('confiance', models.FloatField()),
                ('alerte', models.BooleanField(default=False)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions_performance', to='agents.agent')),
            ],
        ),
    ]
