# Generated by Django 4.2.17 on 2025-06-06 23:54

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('ai_tools', '0003_optimisationplanning_recommandationformation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysesentiment',
            name='interaction',
        ),
        migrations.RemoveField(
            model_name='analysesentiment',
            name='polarite',
        ),
        migrations.RemoveField(
            model_name='analysesentiment',
            name='subjectivite',
        ),
        migrations.AddField(
            model_name='analysesentiment',
            name='confiance',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analysesentiment',
            name='date_analyse',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='analysesentiment',
            name='score_sentiment',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analysesentiment',
            name='sentiment',
            field=models.CharField(default='neutre', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analysesentiment',
            name='texte_feedback',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
