# Generated by Django 4.2.17 on 2025-06-06 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_tools', '0004_auto_20250607_0054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysesentiment',
            name='resultat',
        ),
    ]
