# Generated by Django 4.2.17 on 2025-06-07 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_tools', '0005_auto_20250607_0059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysesentiment',
            name='date',
        ),
    ]
