# Generated by Django 4.2.17 on 2025-06-07 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_tools', '0006_auto_20250607_0103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysesentiment',
            options={'ordering': ['-date_analyse']},
        ),
    ]
