# Generated by Django 4.2.17 on 2025-06-07 07:40

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kpis', '0001_initial'),
        ('agents', '0001_initial'),
    ]

    operations = [
        # Supprimer les anciens KPIs qui n'ont pas d'agent associé
        migrations.RunSQL(
            'DELETE FROM kpis_kpi;',
            reverse_sql='SELECT 1;'
        ),
        # Ajouter le champ type
        migrations.AddField(
            model_name='kpi',
            name='type',
            field=models.CharField(max_length=20, choices=[
                ('satisfaction', 'Satisfaction client'),
                ('performance', 'Performance'),
                ('qualite', 'Qualité'),
                ('formation', 'Formation')
            ], default='performance')
        ),
        # Ajouter le champ agent
        migrations.AddField(
            model_name='kpi',
            name='agent',
            field=models.ForeignKey(
                to='agents.agent',
                on_delete=models.CASCADE,
                related_name='kpis'
            )
        )
    ]
