# Generated by Django 4.2.17 on 2025-06-07 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpis', '0002_auto_20250607_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpi',
            name='type',
            field=models.CharField(choices=[('satisfaction', 'Satisfaction client'), ('performance', 'Performance'), ('qualite', 'Qualité'), ('formation', 'Formation')], max_length=20),
        ),
    ]
