# Generated by Django 4.2.17 on 2025-06-06 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('missions', '0003_kpi_mission_kpis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('statut', models.CharField(choices=[('nouvelle', 'Nouvelle'), ('en_cours', 'En cours'), ('resolue', 'Résolue'), ('annulee', 'Annulée')], default='nouvelle', max_length=20)),
                ('priorite', models.IntegerField(default=0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requetes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Requête',
                'verbose_name_plural': 'Requêtes',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='PreferenceContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horaires_preferes', models.CharField(help_text='Ex: 9h-12h, 14h-17h', max_length=200)),
                ('jours_exclus', models.CharField(blank=True, help_text='Ex: Lundi, Mercredi', max_length=200)),
                ('mode_contact_prefere', models.CharField(default='telephone', max_length=50)),
                ('numero_telephone', models.CharField(max_length=20)),
                ('email_contact', models.EmailField(max_length=254)),
                ('ne_pas_deranger', models.BooleanField(default=False)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences_contact', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Préférence de contact',
                'verbose_name_plural': 'Préférences de contact',
            },
        ),
        migrations.CreateModel(
            name='HistoriqueAppel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_appel', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(max_length=50)),
                ('commentaire', models.TextField(blank=True)),
                ('duree', models.DurationField(blank=True, null=True)),
                ('prochain_contact', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_appels', to=settings.AUTH_USER_MODEL)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_appels', to='missions.mission')),
            ],
            options={
                'verbose_name': "Historique d'appel",
                'verbose_name_plural': 'Historique des appels',
                'ordering': ['-date_appel'],
            },
        ),
    ]
