# Generated by Django 4.2.17 on 2025-06-05 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0001_initial'),
        ('formations', '0002_rename_date_participation_date_inscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formation',
            name='mission',
        ),
        migrations.AddField(
            model_name='formation',
            name='duree',
            field=models.PositiveIntegerField(default=1, help_text='Durée en heures'),
        ),
        migrations.AddField(
            model_name='formation',
            name='missions',
            field=models.ManyToManyField(blank=True, related_name='formations', to='missions.mission'),
        ),
        migrations.AddField(
            model_name='participation',
            name='commentaire',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='participation',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('validee', 'Validée'), ('refusee', 'Refusée')], default='en_attente', max_length=20),
        ),
    ]
