# Generated by Django 4.2.17 on 2025-06-07 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0003_remove_formation_mission_formation_duree_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='satisfaction',
            field=models.FloatField(
                null=True,
                blank=True,
                help_text='Note de satisfaction de 0 à 1'
            ),
        ),
    ]
