# Generated by Django 4.2.17 on 2025-06-07 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0004_auto_20250607_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='type',
            field=models.CharField(choices=[('technique', 'Technique'), ('soft_skills', 'Soft Skills'), ('produit', 'Produit'), ('process', 'Processus'), ('reglementaire', 'Réglementaire')], default='technique', max_length=50),
        ),
    ]
